version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: projekt-REST-wti-2020
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

  wti-proj:
    build: .
    image: wti-proj
    environment:
      APP_MODULE: app.__init__:app
    ports:
      - 80:80