version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: baloo
      POSTGRES_PASSWORD: projekt-REST-wti-2020
      POSTGRES_DB: projekt-rest
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

  wti-proj:
    build:
      context: .
      dockerfile: ./docker/wti-proj/Dockerfile
    depends_on:
      - db
      - redis
    environment:
      APP_MODULE: app.__init__:app
    volumes:
      - ./app:/app/app
    ports:
      - 80:80